---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-external-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-external
  {{ end }}
{{ file .INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
        - {{ .PRODUCTION_URL }}
        - "admin-ui.prod.report-terrorist-material.homeoffice.gov.uk"
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-external
      {{ else }}
      secretName: {{ .APP_NAME }}-external
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - host: {{ .PRODUCTION_URL }}
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
              {{ else }}
              serviceName: {{ .APP_NAME }}-openresty
              {{ end }}
              servicePort: 8443
