---
apiVersion: v1
kind: ConfigMap
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-config
  {{ else }}
  name: {{ .APP_NAME }}-config
  {{ end }}
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: {{ .APP_NAME }}
    {{ end }}
data:
  haproxy.cfg: |
{{ file .HA_PROXY_SETTINGS | indent 4 }}
