version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  hof-rotm-app:
    env_file: devcontainer.env
    build:
      context: .
      dockerfile: Dockerfile
    
    networks:
      - rotm-shared-network
    ports:
      - "8080:8080"
    hostname: hof-app
    depends_on:
      - redis

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app:cached
      # Path to the Google Cloud Application Default Credentials (used for authentication)
      - ${HOME}/.config/gcloud/application_default_credentials.json:/tmp/gcp-creds.json:ro

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: sleep infinity

  redis:
    image: "redis:alpine"
    networks:
      - rotm-shared-network
    hostname: hof-redis
    ports:
      - "6379:6379"

networks:
  rotm-shared-network:
    driver: bridge
 
