---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: waf-admin-ui-external-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: waf-admin-ui-ingress-external
  {{ end }}
{{ file .ADMIN_UI_INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - waf-admin-ui-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - admin-ui.uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - admin-ui.stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
        - admin-ui.prod.report-terrorist-material.homeoffice.gov.uk
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-external
      {{ else }}
      secretName: {{ .APP_NAME }}-external
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: waf-admin-ui-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: admin-ui.uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: admin-ui.stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - host: admin-ui.prod.report-terrorist-material.homeoffice.gov.uk
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
              {{ else }}
              serviceName: {{ .APP_NAME }}-openresty
              {{ end }}
              servicePort: 8082
